### ISSUE TITLE
Replacing old images on leadership page

### ISSUE THREAD

**Issue by apple-juice** [LykkeCity/LykkePublicWebsite#12]
path /public/img/corp/leadership/big/

new images:
https://github.com/LykkeCity/LykkeWeb/blob/master/public/img/corp/leadership/big/2-ivliev.jpg
https://github.com/LykkeCity/LykkeWeb/blob/master/public/img/corp/leadership/big/6-steblyuk.JPG

**Comment by Sokel** [comment]
covered by 7b28ed69dec553d54bb73152c08df00b633b62cf

**Comment by Sokel** [comment]
closed in release 1.1.167 
https://github.com/LykkeCity/LykkePublicWebsite/releases/tag/1.1.167
