### ISSUE TITLE
New footer markup

### ISSUE THREAD

**Issue by apple-juice** [LykkeCity/LykkePublicWebsite#13]
Footer markup was changed, can see here – https://github.com/LykkeCity/LykkeWeb/commit/e14f25fd2a5be5b887f700a347351bf595172855#diff-366f1b0762f4bf7b17d28e040f65b8a0

**Comment by Sokel** [comment]
covered by c7522b2eee2c6d90903d43d0cc57375a4382827e

**Comment by Sokel** [comment]
closed in release 1.1.167 
https://github.com/LykkeCity/LykkePublicWebsite/releases/tag/1.1.167
