### ISSUE TITLE
Checking functions.js file

### ISSUE THREAD

**Issue by apple-juice** [LykkeCity/LykkePublicWebsite#14]
https://www.dev.lykke.com/ has old function.js file, thats why .content has аn unnecessary padding-top

Check this file – https://github.com/LykkeCity/LykkeWeb/blob/master/public/js/functions.js
Minified version – https://github.com/LykkeCity/LykkeWeb/blob/master/dist/js/functions.js

**Comment by Sokel** [comment]
Covered by 6ab781cdc1d27875cfd3aadfa25d046b3b79bac7
