### ISSUE TITLE
Required fields don't work in Safari

### ISSUE THREAD

**Issue by olgachuprikova** [LykkeCity/LykkePublicWebsite#15]
Accelerate me page. https://www.test.lykke.com/b2b-deploy

**Comment by olgachuprikova** [comment]
And Join as Blockchain accelerator page. https://www.test.lykke.com/b2b-join

**Comment by Sokel** [comment]
closed in release 1.1.167 
https://github.com/LykkeCity/LykkePublicWebsite/releases/tag/1.1.167
