### ISSUE TITLE
Blog - Auto Generating Meta Descriptions 

### ISSUE THREAD

**Issue by JoshLKWhite** [LykkeCity/LykkePublicWebsite#16]
Blog posts currently have no Meta Descriptions. 

Please add auto populating meta descriptions to blog posts. Which use the first 155 characters from the post and then finish with a "...". 

For search engine presentation.

**Comment by Sokel** [comment]
covered for blog and news post by 21f8a519e29c39e4c4c27293458a7842098f1010
