### ISSUE TITLE
SEO - .htaccess file modifications

### ISSUE THREAD

**Issue by olgachuprikova** [LykkeCity/LykkePublicWebsite#19]
Can you please add these edits to the .htaccess file?
#Image Expires Tag
<IfModule mod_expires.c>
ExpiresActive on
ExpiresByType image/jpg "access plus 1 month"
ExpiresByType image/jpeg "access plus 1 month"
ExpiresByType image/gif "access plus 1 month"
ExpiresByType image/png "access plus 1 month"
ExpiresByType image/svg "access plus 1 month"
</IfModule>
#Libwww-perl Access
RewriteCond %
{HTTP_USER_AGENT}
libwww-perl.*
RewriteRule .* ? [F,L]
Thanks!

Transfer from JIRA LKKCOM board

**Comment by Sokel** [comment]
Выполнено. Проверил.
