### ISSUE TITLE
CMS redirects - correction

### ISSUE THREAD

**Issue by LenaMechenkova** [LykkeCity/LykkePublicWebsite#3]
https://www.lykke.com/control/redirects
Please change the words "redirect with" to "redirect from" in the first box.

**Comment by Sokel** [comment]
cover under b3daa32d94bcad260deecb50d24e0117882d9ed1 in dev branch

**Comment by Sokel** [comment]
closed in release 1.1.167 
https://github.com/LykkeCity/LykkePublicWebsite/releases/tag/1.1.167
