### ISSUE TITLE
SEO tasks June - (2)-Google webmaster

### ISSUE THREAD

**Issue by DmitriyGerasyuto** [LykkeCity/LykkePublicWebsite#41]
**Первый вариант** 
Чтобы подтвердить права это необходимо добавить во внутреннюю директорию сайта в папку где размещен sitemap.xml файл верификации https://yadi.sk/d/whJR1zQ93K5Vtz 

**Второй вариант** 
Скопируй указанный ниже метатег и вставь его на главную страницу сайта. Он должен находиться в разделе <head> перед первым разделом <body>.
https://yadi.sk/i/m43hfrUl3KBYK7

Пример https://yadi.sk/i/5SRXbckH3KBX3C

**Comment by DmitriyGerasyuto** [comment]
<meta name="google-site-verification" content="-3oXJnaspLel2iCBy5H0-BvOXfPJ9i1jhJEV6LQn1Lk" />

**Comment by DmitriyGerasyuto** [comment]
@Sokel когда добавишь метатег? Мне надо сайт проверить на ошибки.

**Comment by Sokel** [comment]
Done.
