### ISSUE TITLE
SEO tasks June - (6) - SSL certificate

### ISSUE THREAD

**Issue by DmitriyGerasyuto** [LykkeCity/LykkePublicWebsite#45]
SSL сертификат на страницах 
https://www.lykke.com/company/news 
https://www.lykke.com/city/blog/lykke_wallet_ethereum_integration 
https://www.lykke.com/city/blog 
в браузерах отображается как не заверенный. Из-за чего выводится сообщение о незащищенном соединении: https://yadi.sk/i/RnK6K0XQ3K5oTD 

Необходимо на данных страницах  настроить SSL сертификат чтобы не возникало сообщений о незащищенном соединении.

**Comment by DmitriyGerasyuto** [comment]
@Sokel разобрался в чем причина незащищенного соединения?

**Comment by Sokel** [comment]
Done.
