### ISSUE TITLE
SEO tasks June - (8) - Title

### ISSUE THREAD

**Issue by DmitriyGerasyuto** [LykkeCity/LykkePublicWebsite#47]
Необходимо уникализировать теги title на страницах согласно приложенному файлу: 
[lykke.com-news-title.xlsx](https://github.com/LykkeCity/LykkePublicWebsite/files/1075061/lykke.com-news-title.xlsx)

**Comment by DmitriyGerasyuto** [comment]
@Sokel когда реализуешь задачу ?

**Comment by Sokel** [comment]
Covered in https://github.com/LykkeCity/CompetitionPlatform/pull/5

**Comment by Sokel** [comment]
Move to Comepetition platform.
Covered with https://github.com/LykkeCity/CompetitionPlatform/commit/df868a4942481230ad136caa91969918c0c46678
