### ISSUE TITLE
Move static pages on production && update header

### ISSUE THREAD

**Issue by apple-juice** [LykkeCity/LykkePublicWebsite#7]
https://github.com/LykkeCity/LykkeWeb/blob/master/public/b2b.html
https://github.com/LykkeCity/LykkeWeb/blob/master/public/b2b_deploy.html
https://github.com/LykkeCity/LykkeWeb/blob/master/public/b2b_join.html
https://github.com/LykkeCity/LykkeWeb/blob/master/public/invest.html

demo – https://lykkecity.github.io/LykkeWeb/public/

Feel free to contact me for any questions – telegram: @daycoder

**Comment by Sokel** [comment]
closed in release 1.1.167 
https://github.com/LykkeCity/LykkePublicWebsite/releases/tag/1.1.167
