### ISSUE TITLE
Problems with mobile version

### ISSUE THREAD

**Issue by olgachuprikova** [LykkeCity/LykkePublicWebsite#8]
1. Logout button should be "Sign out" 
2. Scroll in the side menu
![img_0585](https://cloud.githubusercontent.com/assets/26599993/24213438/3d82bd5e-0f54-11e7-8fd9-20f2fe20b7e6.PNG)
![img_0677](https://cloud.githubusercontent.com/assets/26599993/24213441/3db2391c-0f54-11e7-9f89-9b76c6db7591.jpeg)
![img_0678](https://cloud.githubusercontent.com/assets/26599993/24213440/3db20dc0-0f54-11e7-8737-b59981c8cb44.jpeg)

**Comment by Sokel** [comment]
1) This trouble is covered by new header by https://github.com/LykkeCity/LykkePublicWebsite/issues/7
2) Shooting in new header exactly by b42e2991db32c88cb280a3d67e4c41e59e79099f

**Comment by olgachuprikova** [comment]
1. Problem with scroll is not solved. 
2. Impossible to logout, because when you click on the user's icon nothing happens

**Comment by Sokel** [comment]
closed in release 1.1.167 
https://github.com/LykkeCity/LykkePublicWebsite/releases/tag/1.1.167
