### ISSUE TITLE
Error 404 when trying to login (test server)

### ISSUE THREAD

**Issue by olgachuprikova** [LykkeCity/LykkePublicWebsite#9]
![2017-03-21 15 13 57](https://cloud.githubusercontent.com/assets/26599993/24216324/9bcc321a-0f5d-11e7-9cc9-b373b9d5c132.png)

**Comment by Sokel** [comment]
This instance controlled by @Greyewi

**Comment by Sokel** [comment]
closed, not needed in tune process
